"""add_timestamp_to_order

Revision ID: 79bd8728390c
Revises: a8cceb0a4adf
Create Date: 2025-06-02 23:06:18.858870

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79bd8728390c"
down_revision = "a8cceb0a4adf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
