"""create_orders_table

Revision ID: badb8dfa8be3
Revises:
Create Date: 2025-05-30 22:01:57.759595

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "badb8dfa8be3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
